language: node_js
node_js:
  - 12

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script:
        - yarn test:unit

deploy:
  provider: heroku
  app: made-up-world-vuejs
  api_key:
    secure: 5db91f53-02fa-40b9-ac52-c6942dbe8e75
