language: node_js
node_js:
- 12
os: linux
dist: xenial
branches:
  only:
  - master
jobs:
  include:
  - stage: test
    script:
    - yarn test:unit
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: H2gVvFPLuS84TzrjUdIezD0sIw4kHa/flnGxB4auRM3uI9Tvs1iQEELQ86DuHsLTSKvCupi48KhwrqTqttJYLjBlJnrBMFDBNuzBaV0pxkQAhUTbzmkvNCPNEc85Q3yQbqv/LvvUJNLVFuCQYGpL/vwyC5Z0XJuE9oPEFtVINbsqC70Fs00HKOiylhm2yZwhmEYoPd6iQB7EqC4KF79Zw158+bbSVS9v+jobetZfJoTDgAjT8fHf7VAn2GxVHDVScRIMCPTx9u/g7Id2Yh7W5qYr/khMpOxp8epdYFaI3BMrKu1eLyVl8GmDD+yTf+8/v7bhP2f6AugCgcNDtvkDhx6bmjLkj9Gyd400JTkkrzdNDCR+zuQnOrFwm6IMgaKdFyXkyD114v2HvwKBjDXM7UAJYcx1LmRCIb9I8trH9SUQJ+Wh7Gy4ooqhMf6PnrqxkWKQGGedc0Y2cIsHO8Jm48vq/TSqtE1Q9doLcIDGoFIgigAwQxx+It31tRXGST/z8l0XLNl+4lDsOicVZ2G4hR+JNTbV9lI4Mf5CJWFiZBRHqnPDyKgvd7i+cX61PVMetwCWpi9hhSUYBDD6BsJTXKOuAeT9vNgr0X6tO8j4hmktQYyBckqGGw4eobSuy00ZrHt/8mbYKMHTDXZHrXNu4cPgav1U2dq349YRLKd6SPg=
  app: made-up-world-vuejs
  on:
    repo: mrWD/made-up-world-vuejs
