export const TOKEN: 'TOKEN' = 'TOKEN';

export const GET_PAGES: 'GET_PAGES' = 'GET_PAGES';
export const SAVE_PAGE: 'SAVE_PAGE' = 'SAVE_PAGE';

export const GET_STORY_LIST: 'GET_STORY_LIST' = 'GET_STORY_LIST';
export const GET_STORY: 'GET_STORY' = 'GET_STORY';
export const GET_ALL_PAGES: 'GET_ALL_PAGES' = 'GET_ALL_PAGES';
export const GET_PAGE_NUMBER: 'GET_PAGE_NUMBER' = 'GET_PAGE_NUMBER';
export const GET_PAGE_COUNT: 'GET_PAGE_COUNT' = 'GET_PAGE_COUNT';

export const GET_TOKEN: 'GET_TOKEN' = 'GET_TOKEN';
export const GET_AUTH_INFO: 'GET_AUTH_INFO' = 'GET_AUTH_INFO';

export const GET_USER_INFO: 'GET_USER_INFO' = 'GET_USER_INFO';
export const GET_USER_LIST: 'GET_USER_LIST' = 'GET_USER_LIST';
export const GET_IMAGE_DESTINATION: 'GET_IMAGE_DESTINATION' = 'GET_IMAGE_DESTINATION';

export const GET_CHAT_LIST: 'GET_CHAT_LIST' = 'GET_CHAT_LIST';
export const GET_CHAT: 'GET_CHAT' = 'GET_CHAT';
export const GET_MSG_LIST: 'GET_MSG_LIST' = 'GET_MSG_LIST';
export const GET_MSG: 'GET_MSG' = 'GET_MSG';


export const UPDATE_REQUEST_COUNT: 'UPDATE_REQUEST_COUNT' = 'UPDATE_REQUEST_COUNT';
export const ADD_ERROR: 'ADD_ERROR' = 'ADD_ERROR';
export const REMOVE_ERROR: 'REMOVE_ERROR' = 'REMOVE_ERROR';
